// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP7l901Lu9JfjwRnvq1dLCZg1oqkOW1yM',
    appId: '1:329838166206:web:f64f469c21a526a9d85eef',
    messagingSenderId: '329838166206',
    projectId: 'logistigo-ad3d9',
    authDomain: 'logistigo-ad3d9.firebaseapp.com',
    storageBucket: 'logistigo-ad3d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfXN9NVAOi7TIN_dmO2fdiKYwk5ot2ss',
    appId: '1:329838166206:android:620aaf741986cd08d85eef',
    messagingSenderId: '329838166206',
    projectId: 'logistigo-ad3d9',
    storageBucket: 'logistigo-ad3d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXzWY7isr9CDC19zUS8hTlCzXmB2fj5PI',
    appId: '1:329838166206:ios:654a18a790104436d85eef',
    messagingSenderId: '329838166206',
    projectId: 'logistigo-ad3d9',
    storageBucket: 'logistigo-ad3d9.firebasestorage.app',
    iosBundleId: 'com.example.logistigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXzWY7isr9CDC19zUS8hTlCzXmB2fj5PI',
    appId: '1:329838166206:ios:654a18a790104436d85eef',
    messagingSenderId: '329838166206',
    projectId: 'logistigo-ad3d9',
    storageBucket: 'logistigo-ad3d9.firebasestorage.app',
    iosBundleId: 'com.example.logistigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP7l901Lu9JfjwRnvq1dLCZg1oqkOW1yM',
    appId: '1:329838166206:web:05fa53ad217cb373d85eef',
    messagingSenderId: '329838166206',
    projectId: 'logistigo-ad3d9',
    authDomain: 'logistigo-ad3d9.firebaseapp.com',
    storageBucket: 'logistigo-ad3d9.firebasestorage.app',
  );
}
